### ISSUE TITLE
issue with creating a new DiSSCo user

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/disscover#51]
when creating a new user, (new email account) you can login with an identity provider from the list but then you see no username or link to your profile/logout once you are logged in.

**Comment by TomDijkema** [comment]
Hi Wouter,

The problem is likely caused by a false conditional statement. When logging in for the first time it should check if the user object is empty to add the new user record to the database. However, it checked on the plain user object, which if not existent, is still an empty object. Empty objects count as a true value, hence the conditional to trigger the user addition was not triggered.

Changed the conditional to check if the user object is empty instead of existent.
